# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [138]:
import torch
import numpy as np

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [35]:
tensor = torch.zeros(8, 8)
tensor[7] = torch.tensor([4., 3., 2., 6., 5., 2., 3., 4.])
tensor[6] = torch.ones(1, 8)
tensor[0] = tensor[7]*(-1)
tensor[1] = tensor[6]*(-1)
tensor

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [12]:
torch.arange(2,22,2)*torch.arange(3,23,2)

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [54]:
torch.arange(0,7).repeat(11, 1)+torch.transpose(torch.arange(1,110, 10).repeat(7, 1), 0, 1)

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [66]:
def tekstura(n, m):
  tec = torch.tensor([[0, 1], [2, 3]])
  return tec.repeat(n//2+1, m//2+1)[:n, :m]

tekstura(4, 5)

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

In [76]:
t = torch.FloatTensor(4, 7).uniform_(0, 20)
t = t-torch.min(t)
t/torch.max(t)

tensor([[1.0000, 0.0000, 0.6890, 0.3247, 0.7811, 0.9749, 0.7499],
        [0.7225, 0.4601, 0.7988, 0.9593, 0.2541, 0.3669, 0.2368],
        [0.9852, 0.2270, 0.8485, 0.3183, 0.6418, 0.6871, 0.8727],
        [0.1112, 0.4443, 0.6807, 0.4123, 0.0723, 0.3940, 0.1165]])

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в тензорах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [108]:
ar1 = torch.randint(0, 11, [4, 7])
ar2 = torch.randint(0, 11, [4, 7])
print(ar1)
print(ar2)
torch.max(ar1, ar2)

tensor([[ 9,  7,  3,  1,  7,  5,  3],
        [ 2,  9,  5,  7,  5,  1,  8],
        [ 2,  3,  5,  3,  8,  7,  5],
        [10,  8,  4,  0, 10, 10,  1]])
tensor([[ 1,  9,  8, 10,  3, 10, 10],
        [ 4, 10,  7,  3,  5,  6, 10],
        [ 0,  8,  9,  1,  5,  3,  5],
        [ 0,  4,  0,  6,  0,  9,  9]])


tensor([[ 9,  9,  8, 10,  7, 10, 10],
        [ 4, 10,  7,  7,  5,  6, 10],
        [ 2,  8,  9,  3,  8,  7,  5],
        [10,  8,  4,  6, 10, 10,  9]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [119]:
ar = torch.randint(0, 101, [20])
print(ar)
torch.topk(ar, 2).indices[1]

tensor([63,  3, 86, 24, 17, 11, 80, 94, 72, 99, 34, 26, 71, 80, 30, 74, 66, 40,
        73, 29])


tensor(7)

## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [139]:
torch.arange(1,8)+torch.arange(0,110, 10)[:, np.newaxis]


tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [141]:
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])
a_2d-b_1d[:, np.newaxis]

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
tensor([1, 3, 5, 7])
```

In [151]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])
torch.argwhere(a==b).flatten()

tensor([1, 3, 5, 7])

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
tensor([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [156]:
torch.flip(torch.arange(9).view(3,3), [0, 1])


tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
```

Ожидается результат:

```python
tensor([6, 9, 10])
```

In [164]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=10)]

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `torch.arange(9).reshape(3,3)`

In [175]:
a = torch.arange(9).reshape(3,3)
print(a)
s1 = a[:,0].clone()
a[:,0] = a[:,1]
a[:,1] = s1
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[1, 0, 2],
        [4, 3, 5],
        [7, 6, 8]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [188]:
ar = torch.randint(0, 11, [8, 10])
print(ar)
ind = ar.sum(1).argmin()
print(ind)
print(ar[ind])

tensor([[ 1, 10,  8,  8,  4,  1,  5,  4,  3,  9],
        [ 1,  4,  3,  8,  5,  6,  9,  1,  1,  5],
        [10,  5,  6,  6,  3,  4, 10,  7,  0,  0],
        [ 4,  7,  9,  8,  6,  9,  0,  9,  5,  5],
        [ 2,  2,  1,  5,  9,  0,  2,  3,  7,  6],
        [ 4,  1,  3,  5, 10,  1,  4,  3,  8,  2],
        [ 7,  1, 10,  0,  6,  5,  2,  1,  0,  8],
        [ 7,  7,  0,  4,  1,  1,  4,  4, 10,  6]])
tensor(4)
tensor([2, 2, 1, 5, 9, 0, 2, 3, 7, 6])


1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [193]:
ar = torch.randint(0, 101, [20])
print(ar)
ar[ar<30]=30
ar[ar>70]=70
ar

tensor([ 0, 52, 55, 41, 19, 58, 82, 66, 63, 97, 67, 47, 65,  0, 12, 86,  5, 41,
        35, 53])


tensor([30, 52, 55, 41, 30, 58, 70, 66, 63, 70, 67, 47, 65, 30, 30, 70, 30, 41,
        35, 53])

1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [198]:
ar1 = torch.randint(0, 11, [30, 3])
ar2 = torch.randint(0, 11, [30, 3])
ar1[ar1>ar2].sum()

tensor(331)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [206]:
ar1 = torch.randint(0, 11, [20, 20])
print(ar1)
ind = torch.arange(19)
ar1[ind, ind+1]

tensor([[ 8,  6,  8,  2, 10,  3,  2,  5, 10, 10,  7,  0,  5,  4,  3,  7,  5, 10,
          4,  3],
        [ 7,  7,  7,  0, 10,  2,  4,  2,  7,  7,  3,  6,  2,  7, 10,  9,  3,  8,
          9, 10],
        [ 4, 10,  8,  8,  6,  7,  7,  2,  4,  3,  9,  7,  8,  6,  7,  2,  1,  4,
          1,  4],
        [ 3,  5,  0,  6,  0,  0,  8,  5,  1,  1,  2,  8,  5,  5,  3,  0,  1,  3,
          9,  0],
        [10, 10,  1,  5, 10,  3,  4,  8,  5,  6,  5,  7,  8,  5,  1,  3, 10,  7,
          2,  3],
        [ 2,  4,  1, 10,  5,  0, 10,  6,  9,  1,  2, 10,  9,  0,  2,  1,  4,  2,
          0,  0],
        [ 6,  1,  4,  6,  7,  2,  3, 10,  6, 10,  1,  1,  4, 10,  3,  0,  6,  1,
          8,  3],
        [ 5,  6,  1,  4,  4,  3,  8,  8,  3,  9,  9,  9,  4,  0,  9,  3,  9,  0,
          6,  9],
        [ 0,  0,  2,  3,  1,  2,  5,  9,  4,  5,  8,  7,  0,  9,  0,  2, 10,  2,
          6,  6],
        [ 9,  9,  4,  2, 10, 10,  0,  8,  6,  6,  6,  7,  6,  5, 10, 10,  6,  5,
          2,  3],
        [ 

tensor([ 6,  7,  8,  0,  3, 10, 10,  3,  5,  6,  4,  8,  8,  0,  4,  3,  0,  2,
         8])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [212]:
ar1 = torch.randint(0, 11, [5, 10])
ar2 = torch.randint(0, 11, [5, 10])
print(ar1)
print(ar2)
ar1[ar1==ar2] = ar1[ar1==ar2]*2
print(ar1)

tensor([[ 2,  7,  0,  3,  2,  1,  8,  4,  7,  4],
        [ 2,  4, 10,  6,  8,  6,  2,  7,  7,  5],
        [ 2,  2,  6,  1,  5,  3,  5,  5,  4,  9],
        [ 1,  4,  5,  4,  3,  2,  9,  6,  0, 10],
        [ 6,  1,  1,  5,  6,  5,  1,  1,  5,  5]])
tensor([[ 9,  9,  0,  5,  2,  5,  0,  2,  4,  3],
        [ 2,  7,  8,  5,  6,  9,  1,  9,  2,  4],
        [ 1,  2,  4,  0,  0,  3,  9,  0,  9,  0],
        [ 7, 10,  5,  7,  7,  8,  2,  5,  5,  4],
        [ 2,  4,  2,  0,  5,  6,  9,  4,  9,  8]])
tensor([[ 2,  7,  0,  3,  4,  1,  8,  4,  7,  4],
        [ 4,  4, 10,  6,  8,  6,  2,  7,  7,  5],
        [ 2,  4,  6,  1,  5,  6,  5,  5,  4,  9],
        [ 1,  4, 10,  4,  3,  2,  9,  6,  0, 10],
        [ 6,  1,  1,  5,  6,  5,  1,  1,  5,  5]])


1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [215]:
ar1 = torch.randint(0, 11, [4, 7])
ar2 = torch.randint(0, 11, [4, 7])
ar3 = torch.randint(0, 11, [4, 7])
print(ar1)
print(ar2)
print(ar3)
ar1[(ar1>ar2)&(ar1<ar3)] = 0
print(ar1)

tensor([[ 9,  0,  1,  7,  7,  6,  8],
        [ 1,  1,  6,  4,  3,  0,  7],
        [ 7,  6,  2,  5, 10,  3,  8],
        [ 2, 10,  9,  6,  9, 10,  4]])
tensor([[ 7,  2,  6,  8,  3,  3,  0],
        [ 1, 10,  4,  1, 10,  8,  5],
        [ 4,  9,  1,  0,  1,  7,  8],
        [ 2,  2,  6,  2,  8,  4,  1]])
tensor([[ 9,  2,  8,  9,  8, 10,  9],
        [ 9,  8,  6,  5,  2,  5,  2],
        [ 5,  4, 10,  7,  5,  8,  6],
        [ 6,  6,  9,  7,  8,  6,  1]])
tensor([[ 9,  0,  1,  7,  0,  0,  0],
        [ 1,  1,  6,  0,  3,  0,  7],
        [ 7,  6,  0,  0, 10,  3,  8],
        [ 2, 10,  9,  0,  9, 10,  4]])


1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [222]:
ar1 = torch.randint(0, 21, [20, 5])
print(ar1)

print(ar1.max(1))


tensor([[ 9,  5,  5,  7,  8],
        [17, 20,  7,  3, 18],
        [ 7,  8, 16, 20, 18],
        [ 4,  4, 19, 12,  1],
        [18,  5,  8, 14, 12],
        [18, 10, 16,  4, 13],
        [ 2, 20, 15, 15, 16],
        [ 0,  9,  5,  5, 20],
        [10, 13, 16, 14, 12],
        [11, 12, 20,  7, 12],
        [ 5, 20, 14,  8,  8],
        [16,  9,  6, 17,  4],
        [14,  2, 11,  6, 15],
        [ 2, 18, 13,  6,  0],
        [14, 18,  1, 10, 20],
        [14,  9, 16, 14,  3],
        [ 9, 15,  9, 14,  9],
        [10,  9, 12, 16,  9],
        [11, 12, 12, 13, 17],
        [ 1, 12,  7, 12, 14]])
torch.return_types.max(
values=tensor([ 9, 20, 20, 19, 18, 18, 20, 20, 16, 20, 20, 17, 15, 18, 20, 16, 15, 16,
        17, 14]),
indices=tensor([0, 1, 3, 2, 0, 0, 1, 4, 2, 2, 1, 3, 4, 1, 4, 2, 1, 3, 4, 4]))


1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [247]:
ar1 = torch.rand([4, 7])
print(ar1)
ind = np.unravel_index(ar1.argmax(), [4, 7])
print(ind)
ar1[ind[0]+1:, ind[1]+1:]=0
ar1

tensor([[0.1732, 0.0254, 0.7420, 0.1906, 0.7086, 0.9803, 0.7102],
        [0.3709, 0.9680, 0.1340, 0.9875, 0.7241, 0.2990, 0.7214],
        [0.2976, 0.0301, 0.5326, 0.5187, 0.6183, 0.8090, 0.4843],
        [0.0777, 0.6487, 0.0337, 0.9122, 0.2824, 0.8479, 0.6876]])
(1, 3)


tensor([[0.1732, 0.0254, 0.7420, 0.1906, 0.7086, 0.9803, 0.7102],
        [0.3709, 0.9680, 0.1340, 0.9875, 0.7241, 0.2990, 0.7214],
        [0.2976, 0.0301, 0.5326, 0.5187, 0.0000, 0.0000, 0.0000],
        [0.0777, 0.6487, 0.0337, 0.9122, 0.0000, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 